services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    profiles: [ "prod" ]
    environment:
      APP_CONFIG__BOT__TOKEN: ${APP_CONFIG__BOT__TOKEN}

      APP_CONFIG__DB__NAME: ${APP_CONFIG__DB__NAME}
      APP_CONFIG__DB__PASSWORD: ${APP_CONFIG__DB__PASSWORD}
      APP_CONFIG__DB__USER: ${APP_CONFIG__DB__USER}
      APP_CONFIG__DB__HOST: pg
      APP_CONFIG__DB__PORT: ${APP_CONFIG__DB__PORT}
      APP_CONFIG__DB__DRIVER: ${APP_CONFIG__DB__DRIVER}

      APP_CONFIG__DB__ECHO: ${APP_CONFIG__DB__ECHO}
      APP_CONFIG__DB__ECHO_POOL: ${APP_CONFIG__DB__ECHO_POOL}
      APP_CONFIG__DB__POOL_SIZE: ${APP_CONFIG__DB__POOL_SIZE}
      APP_CONFIG__DB__MAX_OVERFLOW: ${APP_CONFIG__DB__MAX_OVERFLOW}

      APP_CONFIG__REDIS__HOST: redis
      APP_CONFIG__REDIS__PORT: ${APP_CONFIG__REDIS__PORT}
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - prod_network

  pg:
    image: postgres:16
    profiles: [ "prod" ]
    container_name: pg_container
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
    ports:
      - ${APP_CONFIG__DB__PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - prod_network

  redis:
    image: redis:latest
    profiles: [ "prod" ]
    container_name: redis_container
    ports:
      - ${APP_CONFIG__REDIS__PORT}:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - prod_network

  pg_test:
    image: postgres:16
    profiles: [ "test" ]
    container_name: pg_test_container
    environment:
      POSTGRES_DB: ${APP_TEST_CONFIG__DB__NAME}
      POSTGRES_USER: ${APP_TEST_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_TEST_CONFIG__DB__PASSWORD}
    ports:
      - ${APP_TEST_CONFIG__DB__PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - test_network

  redis_test:
    image: redis:latest
    profiles: [ "test" ]
    container_name: redis_test_container
    ports:
      - ${APP_TEST_CONFIG__REDIS__PORT}:6379
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - test_network

volumes:
  pg_data:
  redis_data:
networks:
  prod_network:
    driver: bridge
    name: aiogram-prod-network
  test_network:
    driver: bridge
    name: aiogram-test-network