services:
  pg:
    image: postgres:16
    container_name: pg_container
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB__NAME}
      POSTGRES_USER: ${APP_CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB__PASSWORD}
    ports:
      - ${APP_CONFIG__DB__PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3

  pg_test:
    profiles: ["test"] # docker-compose --profile test up -d
    image: postgres:16
    container_name: pg_test_container
    environment:
      POSTGRES_DB: ${APP_CONFIG__DB_TEST__NAME}
      POSTGRES_USER: ${APP_CONFIG__DB_TEST__USER}
      POSTGRES_PASSWORD: ${APP_CONFIG__DB_TEST__PASSWORD}
    ports:
      - ${APP_CONFIG__DB_TEST__PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - ${APP_CONFIG__REDIS__PORT}:6379
    volumes:
      - redis_data:/bitnami/redis/data

volumes:
  pg_data:
  redis_data: